server:
  port: 8961
spring:
  application:
    name: app-front
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:mysql:@127.0.0.1:3306:p2p
    username: root
    password: 12345678
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    cluster:
      nodes: localhost:6379
      max-redirects: 3